version: "3.8"
services:
  stwc_web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: stwc_web
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - stwc_db
    env_file:
      - .env

  stwc_db:
    image: mariadb:10.5
    container_name: stwc_db
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
